### ISSUE TITLE
Load / performance testing setup

### ISSUE THREAD

**Issue by gidili** [openworm/org.wormsim.frontend#64]
- [ ] setup load test for landing page
- [ ] setup load test for WormSim mainpage (user logged in)
- [ ] load test for how long it takes to load a simulation in the geppetto environment

**Comment by mihairaulea** [comment]
Load testing

1) Http calls

In order to test the capabilities and the workload of the Virgo http server, i have used a free instance of loader.io. I have simulated 250 clients in a 1 min timeframe, each requesting the home and setuserinfo pages.
These are the results of the test, with the jvm set to 512 MB max heap.

Response Times

Average	200 ms
Min/Max	165 / 971 ms

Response Counts

Success	100%	
Timeout	0
Network	0

Bandwidth

Sent	25.78 KB
Received	7.53 MB

All in all, everything looks in top shape. No dropped packages, and an average response time of 200ms, which is very good.

2) Websocket capabilities

npm install -g thor
thor --amount 250 ws://localhost:8080/org.geppetto.org/

Output:

Connecting to ws://localhost:8080

  Opened 100 connections
  Opened 200 connections
  Opened 250 connections


Online               7500 milliseconds
Time taken           7225 milliseconds
Connected            250
Disconnected         0
Failed               0
Total transferred    120.46MB
Total received       120.43MB

Durations (ms):

                     min     mean     stddev  median max
Handshaking          217     5036       4094    3902 14451
Latency              0       215         104     205 701

Percentile (ms):

                      50%     66%     75%     80%     90%     95%     98%     98%    100%
Handshaking          3402    6225    8273    9141    11409   12904   13382   13945   14451
Latency              205     246     266     288     371     413     437     443     701

**Comment by mihairaulea** [comment]
http://support.loader.io/article/15-creating-a-test

**Comment by mihairaulea** [comment]
you will also find the api docs here, for complex scenarios: http://support.loader.io/category/42-loaderio-api
