### ISSUE TITLE
User should be able to get back into configuring the worm mode

### ISSUE THREAD

**Issue by slarson** [openworm/org.wormsim.frontend#85]
There doesn't seem to be a UI for going back and configuring your worm.  This should be possible.

**Comment by tarelli** [comment]
@slarson this was discussed in a number of meetings, the decision to not make it possible was a deliberate one. Rationale being that it's not "just" a setting but rather the worm that you created. When you create a character in a videogame you can't change its name of its facial features halfway through  since it would diminish its reality reducing the character to a bunch of fields therefore breaking the suspension of disbelief.

**Comment by gidili** [comment]
@slarson @tarelli we had a few chat about this and we chose not to do it (would be ok to re-do it if they can create another wormsim). In case the fields ever were re-editable though it wouldn't be the entire flow again, just the fields in some settings dialog like we had at the beginning but we got rid of it for the reasons brought above by Matteo.
